[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.18.2"
quilt_mappings = "1.18.2+build.24"
quilt_loader = "0.17.1-beta.2"
quilt_standard_libraries = "1.1.0-beta.19+1.18.2"
quilted_fabric_api = "1.0.0-beta.22+0.56.0-1.18.2"

# Stone Cutter Recipe Tags
#scrt = "3.0.1-fabric"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
quilt_standard_libraries = { module = "org.quiltmc:qsl", version.ref = "quilt_standard_libraries" }
quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
# [bundles]
# example = ["example-a", "example-b", "example-c"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }
